name: ledger_flutter
description: A Flutter plugin to scan, connect & sign transactions using your Ledger Nano devices
version: 1.0.1
homepage: https://developers.ledger.com/
repository: https://github.com/RootSoft/ledger-flutter
issue_tracker: https://github.com/RootSoft/ledger-flutter/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_reactive_ble: ^5.0.3
  ledger_usb: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
